export const JOBS = [
  {
    id: 'plough_barley',
    kind: 'plough',
    field: 'barley_clover',
    acres: 8,
    window: ['I', 'I'],
    prereq: [],
    label: 'Plough barley & clover',
    value: 8,
  },
  {
    id: 'harrow_barley',
    kind: 'harrow',
    field: 'barley_clover',
    acres: 8,
    window: ['I', 'I'],
    prereq: ['plough_barley'],
    label: 'Harrow barley & clover',
    value: 8,
  },
  {
    id: 'sow_barley_clover',
    kind: 'sow',
    field: 'barley_clover',
    acres: 8,
    crop: 'barley+clover',
    window: ['I', 'I'],
    prereq: ['harrow_barley'],
    label: 'Sow barley with clover',
    value: 9,
  },
  {
    id: 'plough_pulses',
    kind: 'plough',
    field: 'pulses',
    acres: 4,
    window: ['I', 'I'],
    prereq: [],
    label: 'Plough pulses close',
    value: 4,
  },
  {
    id: 'harrow_pulses',
    kind: 'harrow',
    field: 'pulses',
    acres: 4,
    window: ['I', 'I'],
    prereq: ['plough_pulses'],
    label: 'Harrow pulses close',
    value: 4,
  },
  {
    id: 'sow_pulses',
    kind: 'sow',
    field: 'pulses',
    acres: 4,
    crop: 'beans/peas/vetch',
    window: ['I', 'I'],
    prereq: ['harrow_pulses'],
    label: 'Sow pulses',
    value: 5,
  },
  {
    id: 'plough_oats_close',
    kind: 'plough',
    field: 'oats_close',
    acres: 3,
    window: ['I', 'I'],
    prereq: [],
    label: 'Plough oats close',
    value: 3,
  },
  {
    id: 'harrow_oats_close',
    kind: 'harrow',
    field: 'oats_close',
    acres: 3,
    window: ['I', 'I'],
    prereq: ['plough_oats_close'],
    label: 'Harrow oats close',
    value: 3,
  },
  {
    id: 'sow_oats_close',
    kind: 'sow',
    field: 'oats_close',
    acres: 3,
    crop: 'oats',
    window: ['I', 'I'],
    prereq: ['harrow_oats_close'],
    label: 'Sow oats',
    value: 3,
  },
  {
    id: 'garden_sow_spring',
    kind: 'garden_plant',
    field: 'homestead',
    acres: 0.25,
    crops: ['onions', 'cabbages', 'carrots'],
    window: ['I', 'I'],
    prereq: [],
    label: 'Plant kitchen garden',
    value: 2,
  },
  {
    id: 'move_sheep_to_clover',
    kind: 'move_livestock',
    field: 'turnips',
    acres: 0,
    window: ['I', 'I'],
    prereq: [],
    label: 'Move sheep to clover hay',
    value: 1,
    to: 'clover_hay',
    from: 'turnips',
  },
  {
    id: 'market_trip',
    kind: 'market',
    window: ['I', 'VIII'],
    prereq: [],
    label: 'Cart goods to market',
    value: 4,
    guard: 'hasTradeNeed',
  },
];
