import { CROPS, PARCEL_KIND } from '../constants.js';

export const DEFAULT_PACK_V1 = {
  version: 1,
  units: { grain: 'bu', hay: 't' },
  estate: {
    farmhouse: { x: 23, y: 14 },
    parcels: [
      {
        key: 'turnips',
        name: 'North Turnip Field',
        acres: 8,
        kind: PARCEL_KIND.ARABLE,
        rotationIndex: 0,
        status: { cropNote: 'Turnip aftermath', stubble: false, tilth: 0.4 },
        x: 40,
        y: 60,
        w: 30,
        h: 12,
      },
      {
        key: 'barley_clover',
        name: 'Barley & Clover',
        acres: 8,
        kind: PARCEL_KIND.ARABLE,
        rotationIndex: 1,
        status: { cropNote: 'Ready for barley & clover', stubble: true, tilth: 0.3 },
        x: 76,
        y: 60,
        w: 30,
        h: 12,
      },
      {
        key: 'clover_hay',
        name: 'Clover Hay',
        acres: 8,
        kind: PARCEL_KIND.ARABLE,
        rotationIndex: 2,
        status: { cropNote: 'Clover aftermath', stubble: false, tilth: 0.35 },
        x: 112,
        y: 60,
        w: 30,
        h: 12,
        pasture: true,
      },
      {
        key: 'wheat',
        name: 'Lower Wheat',
        acres: 8,
        kind: PARCEL_KIND.ARABLE,
        rotationIndex: 3,
        status: { cropNote: 'Winter wheat emerging', stubble: false, tilth: 0.5 },
        x: 40,
        y: 78,
        w: 30,
        h: 12,
        initialCrop: CROPS.WHEAT,
        initialGrowth: 0.35,
      },
      {
        key: 'pulses',
        name: 'Pulse Close',
        acres: 4,
        kind: PARCEL_KIND.CLOSE,
        status: { cropNote: 'Beans & peas fallow', stubble: false, tilth: 0.25 },
        x: 76,
        y: 26,
        w: 26,
        h: 12,
      },
      {
        key: 'flex',
        name: 'Flex Field',
        acres: 6,
        kind: PARCEL_KIND.ARABLE,
        rotationIndex: 0,
        status: { cropNote: 'Awaiting decision', stubble: true, tilth: 0.25 },
        x: 76,
        y: 78,
        w: 28,
        h: 12,
      },
      {
        key: 'oats_close',
        name: 'Oats Close',
        acres: 3,
        kind: PARCEL_KIND.CLOSE,
        status: { cropNote: 'Oat aftermath', stubble: true, tilth: 0.3 },
        x: 30,
        y: 24,
        w: 20,
        h: 11,
      },
      {
        key: 'close_c',
        name: 'Close C',
        acres: 3,
        kind: PARCEL_KIND.CLOSE,
        status: { cropNote: 'Roots lifted', stubble: false, tilth: 0.2 },
        x: 52,
        y: 24,
        w: 24,
        h: 11,
      },
      {
        key: 'orchard',
        name: 'Orchard',
        acres: 2,
        kind: PARCEL_KIND.ORCHARD,
        status: { cropNote: 'Fruit trees budding', stubble: false, tilth: 0 },
        x: 108,
        y: 26,
        w: 24,
        h: 11,
        rows: 0,
        pasture: true,
      },
      {
        key: 'homestead',
        name: 'Homestead Garden',
        acres: 1,
        kind: PARCEL_KIND.GARDEN,
        status: { cropNote: 'Kitchen beds', stubble: false, tilth: 0.4 },
        x: 136,
        y: 26,
        w: 22,
        h: 11,
        rows: 0,
      },
    ],
  },
};
