import { MINUTES_PER_DAY } from '../time.js';

export const NEIGHBOR_FARMS = Object.freeze([
  Object.freeze({
    id: 'southstead',
    name: 'Southstead',
    farmerName: 'Walter',
    farmhouse: Object.freeze({ x: 220, y: 420, w: 18, h: 10 }),
    barn: Object.freeze({ x: 250, y: 422, w: 12, h: 8 }),
    well: Object.freeze({ x: 236, y: 414 }),
    bed: Object.freeze({ x: 226, y: 427 }),
    plots: Object.freeze([
      Object.freeze({
        id: 'southstead_turnips',
        name: 'Turnip Close',
        type: 'arable',
        crop: 'turnips',
        stage: 3,
        x: 262,
        y: 360,
        w: 72,
        h: 112,
      }),
      Object.freeze({
        id: 'southstead_pasture',
        name: 'Sheep Fold',
        type: 'pasture',
        crop: null,
        stage: null,
        x: 186,
        y: 402,
        w: 58,
        h: 86,
      }),
      Object.freeze({
        id: 'southstead_coppice',
        name: 'South Coppice',
        type: 'coppice',
        crop: null,
        stage: null,
        x: 120,
        y: 348,
        w: 320,
        h: 8,
      }),
      Object.freeze({
        id: 'southstead_garden',
        name: 'Kitchen Plot',
        type: 'garden',
        crop: 'herbs',
        stage: 2,
        x: 208,
        y: 432,
        w: 24,
        h: 26,
      }),
    ]),
    schedule: Object.freeze([
      Object.freeze({
        id: 'sleep',
        label: 'Resting',
        start: 0,
        duration: 360,
        waypoints: Object.freeze([{ x: 226, y: 427 }]),
        loop: false,
        linger: 6,
      }),
      Object.freeze({
        id: 'livestock_rounds',
        label: 'Tend Livestock',
        start: 360,
        duration: 120,
        waypoints: Object.freeze([
          { x: 256, y: 425 },
          { x: 236, y: 414 },
          { x: 205, y: 420 },
        ]),
        loop: true,
        linger: 3,
      }),
      Object.freeze({
        id: 'fieldwork',
        label: 'Hoe Turnips',
        start: 480,
        duration: 210,
        waypoints: Object.freeze([
          { x: 284, y: 380 },
          { x: 314, y: 404 },
          { x: 290, y: 446 },
        ]),
        loop: true,
        linger: 2,
      }),
      Object.freeze({
        id: 'midday_meal',
        label: 'Midday Meal',
        start: 690,
        duration: 60,
        waypoints: Object.freeze([{ x: 228, y: 428 }]),
        loop: false,
        linger: 8,
      }),
      Object.freeze({
        id: 'coppice_cutting',
        label: 'Cut Coppice',
        start: 750,
        duration: 210,
        waypoints: Object.freeze([
          { x: 160, y: 350 },
          { x: 260, y: 350 },
          { x: 320, y: 350 },
        ]),
        loop: true,
        linger: 2,
      }),
      Object.freeze({
        id: 'evening_rounds',
        label: 'Evening Rounds',
        start: 960,
        duration: 120,
        waypoints: Object.freeze([
          { x: 256, y: 425 },
          { x: 205, y: 420 },
        ]),
        loop: true,
        linger: 3,
      }),
      Object.freeze({
        id: 'night_rest',
        label: 'Resting',
        start: 1080,
        duration: MINUTES_PER_DAY - 1080,
        waypoints: Object.freeze([{ x: 226, y: 427 }]),
        loop: false,
        linger: 6,
      }),
    ]),
  }),
]);

export default NEIGHBOR_FARMS;
