export const CONFIG_PACK_V1 = Object.freeze({
  version: 1,
  units: { grain: 'bu', hay: 't' },
  time: {
    simMinPerRealMin: 60,
    tickSimMin: 0.5,
    daySimMin: 24 * 60,
    realMsPerMinute: 60 * 1000,
    minutesPerHour: 60,
    workStartMin: 6 * 60,
    workEndMin: 18 * 60,
    daylightAnchors: [
      { monthIndex: 0, workStart: 6 * 60, workEnd: 18 * 60 },
      { monthIndex: 1, workStart: 5 * 60 + 30, workEnd: 19 * 60 + 30 },
      { monthIndex: 2, workStart: 5 * 60, workEnd: 20 * 60 + 30 },
      { monthIndex: 3, workStart: 4 * 60 + 45, workEnd: 21 * 60 },
      { monthIndex: 4, workStart: 5 * 60 + 15, workEnd: 20 * 60 + 30 },
      { monthIndex: 5, workStart: 5 * 60 + 45, workEnd: 19 * 60 + 30 },
      { monthIndex: 6, workStart: 6 * 60 + 30, workEnd: 18 * 60 },
      { monthIndex: 7, workStart: 7 * 60 + 15, workEnd: 17 * 60 },
    ],
    speedMultipliers: {
      PAUSE: 0,
      VERY_SLOW: 0.03,
      SLOW: 0.06,
      NORMAL: 0.12,
      FAST: 0.5,
      ULTRA: 2,
    },
  },
  calendar: {
    months: ['I', 'II', 'III', 'IV', 'V', 'VI', 'VII', 'VIII'],
    daysPerMonth: 20,
  },
  labour: {
    monthlyHours: 640,
    hoursPerDay: 8,
    crewSlots: 4,
    travelStepSimMin: 0.5,
  },
  rates: {
    ploughHarrow: 160,
    sow: 90,
    hoe: 60,
    harvest: 120,
    hayCut: 180,
    loadUnloadMarket: 30,
    gardenHours: 6,
  },
  rules: {
    minGrainReserve: 120,
    sellTurnipThreshold: 200,
    hayMin: 2,
    hayTarget: 6,
    grainKeep: 120,
    grainSurplus: 160,
    cashMin: 5,
    manifestValueMin: 20,
    labourValuePerMin: 0.1,
    marketCooldownSimMin: 24 * 60,
    cartCapacity: 60,
    closeFieldMaxSteps: 120,
    seedMinimums: { barley: 12, pulses: 10, oats: 12, wheat: 12 },
    oatsLowThreshold: 20,
    priceDrift: { months: [6, 7, 8], factor: 0.1 },
    marketHours: { open: 9 * 60, close: 17 * 60 },
    travelPenaltyCap: 5,
    debtHorizonHours: 48,
    manifestDiscounts: { essential: 0.7, seeds: 0.9, default: 1.2 },
    buyUtilityMultiplier: 1.2,
    seedKeys: ['barley', 'pulses', 'oats', 'wheat'],
  },
  estate: {
    farmhouse: { x: 23, y: 14 },
    market: { x: 8, y: 8 },
    parcels: [
      {
        key: 'turnips',
        name: 'North Turnip Field',
        acres: 8,
        kind: 'arable',
        rotationIndex: 0,
        status: { cropNote: 'Turnip aftermath', stubble: false, tilth: 0.4 },
        x: 40,
        y: 60,
        w: 30,
        h: 12,
      },
      {
        key: 'barley_clover',
        name: 'Barley & Clover',
        acres: 8,
        kind: 'arable',
        rotationIndex: 1,
        status: { cropNote: 'Ready for barley & clover', stubble: true, tilth: 0.3 },
        x: 76,
        y: 60,
        w: 30,
        h: 12,
      },
      {
        key: 'clover_hay',
        name: 'Clover Hay',
        acres: 8,
        kind: 'arable',
        rotationIndex: 2,
        status: { cropNote: 'Clover aftermath', stubble: false, tilth: 0.35 },
        x: 112,
        y: 60,
        w: 30,
        h: 12,
        pasture: true,
      },
      {
        key: 'wheat',
        name: 'Lower Wheat',
        acres: 8,
        kind: 'arable',
        rotationIndex: 3,
        status: { cropNote: 'Winter wheat emerging', stubble: false, tilth: 0.5 },
        x: 40,
        y: 78,
        w: 30,
        h: 12,
        initialCrop: 'WHEAT',
        initialGrowth: 0.35,
      },
      {
        key: 'pulses',
        name: 'Pulse Close',
        acres: 4,
        kind: 'close',
        status: { cropNote: 'Beans & peas fallow', stubble: false, tilth: 0.25 },
        x: 76,
        y: 26,
        w: 26,
        h: 12,
      },
      {
        key: 'flex',
        name: 'Flex Field',
        acres: 6,
        kind: 'arable',
        rotationIndex: 0,
        status: { cropNote: 'Awaiting decision', stubble: true, tilth: 0.25 },
        x: 76,
        y: 78,
        w: 28,
        h: 12,
      },
      {
        key: 'oats_close',
        name: 'Oats Close',
        acres: 3,
        kind: 'close',
        status: { cropNote: 'Oat aftermath', stubble: true, tilth: 0.3 },
        x: 30,
        y: 24,
        w: 20,
        h: 11,
      },
      {
        key: 'close_c',
        name: 'Close C',
        acres: 3,
        kind: 'close',
        status: { cropNote: 'Roots lifted', stubble: false, tilth: 0.2 },
        x: 52,
        y: 24,
        w: 24,
        h: 11,
      },
      {
        key: 'orchard',
        name: 'Orchard',
        acres: 2,
        kind: 'orchard',
        status: { cropNote: 'Fruit trees budding', stubble: false, tilth: 0 },
        x: 108,
        y: 26,
        w: 24,
        h: 11,
        rows: 0,
        pasture: true,
      },
      {
        key: 'homestead',
        name: 'Homestead Garden',
        acres: 1,
        kind: 'garden',
        status: { cropNote: 'Kitchen beds', stubble: false, tilth: 0.4 },
        x: 136,
        y: 26,
        w: 22,
        h: 11,
        rows: 0,
      },
    ],
  },
});

export default CONFIG_PACK_V1;
