export const CONFIG_PACK_V1 = Object.freeze({
  version: 1,
  units: { grain: 'bu', hay: 't' },
  time: {
    simMinPerRealMin: 60,
    tickSimMin: 0.5,
    daySimMin: 24 * 60,
    realMsPerMinute: 60 * 1000,
    minutesPerHour: 60,
    workStartMin: 6 * 60,
    workEndMin: 18 * 60,
    daylightAnchors: [
      { monthIndex: 0, workStart: 6 * 60, workEnd: 18 * 60 },
      { monthIndex: 1, workStart: 5 * 60 + 30, workEnd: 19 * 60 + 30 },
      { monthIndex: 2, workStart: 5 * 60, workEnd: 20 * 60 + 30 },
      { monthIndex: 3, workStart: 4 * 60 + 45, workEnd: 21 * 60 },
      { monthIndex: 4, workStart: 5 * 60 + 15, workEnd: 20 * 60 + 30 },
      { monthIndex: 5, workStart: 5 * 60 + 45, workEnd: 19 * 60 + 30 },
      { monthIndex: 6, workStart: 6 * 60 + 30, workEnd: 18 * 60 },
      { monthIndex: 7, workStart: 7 * 60 + 15, workEnd: 17 * 60 },
    ],
    speedMultipliers: {
      PAUSE: 0,
      VERY_SLOW: 0.03,
      SLOW: 0.06,
      NORMAL: 0.12,
      FAST: 0.5,
      ULTRA: 2,
    },
  },
  calendar: {
    months: ['I', 'II', 'III', 'IV', 'V', 'VI', 'VII', 'VIII'],
    daysPerMonth: 20,
  },
  labour: {
    monthlyHours: 640,
    hoursPerDay: 8,
    crewSlots: 4,
    travelStepSimMin: 0.5,
  },
  rates: {
    ploughHarrow: 160,
    sow: 90,
    hoe: 60,
    harvest: 120,
    hayCut: 180,
    loadUnloadMarket: 30,
    gardenHours: 6,
  },
  rules: {
    minGrainReserve: 120,
    sellTurnipThreshold: 200,
    hayMin: 2,
    hayTarget: 6,
    grainKeep: 120,
    grainSurplus: 160,
    cashMin: 5,
    manifestValueMin: 20,
    labourValuePerMin: 0.1,
    marketCooldownSimMin: 24 * 60,
    cartCapacity: 60,
    closeFieldMaxSteps: 180,
    seedMinimums: { barley: 12, pulses: 10, oats: 12, wheat: 12 },
    oatsLowThreshold: 20,
    priceDrift: { months: [6, 7, 8], factor: 0.1 },
    marketHours: { open: 9 * 60, close: 17 * 60 },
    travelPenaltyCap: 5,
    debtHorizonHours: 48,
    manifestDiscounts: { essential: 0.7, seeds: 0.9, default: 1.2 },
    buyUtilityMultiplier: 1.2,
    seedKeys: ['barley', 'pulses', 'oats', 'wheat'],
  },
  estate: {
    farmhouse: { x: 230, y: 200, w: 20, h: 12 },
    market: { x: 8, y: 8 },
    byre: { x: 260, y: 200, w: 12, h: 8 },
    parcels: [
      // Coppice spanning the northern boundary
      {
        key: 'coppice',
        name: 'Coppice',
        acres: 2,
        kind: 'coppice',
        status: { cropNote: 'Woodland', stubble: false, tilth: 0 },
        x: 120,
        y: 20,
        w: 320,
        h: 8,
        rows: 0,
      },
      // Homestead parcels
      {
        key: 'homestead',
        name: 'Homestead Garden',
        acres: 1,
        kind: 'garden',
        status: { cropNote: 'Kitchen beds', stubble: false, tilth: 0.4 },
        x: 220,
        y: 240,
        w: 40,
        h: 40,
        rows: 0,
      },
      {
        key: 'orchard',
        name: 'Orchard',
        acres: 2,
        kind: 'orchard',
        status: { cropNote: 'Fruit trees', stubble: false, tilth: 0 },
        x: 160,
        y: 240,
        w: 50,
        h: 50,
        rows: 0,
        pasture: true,
      },
      // Arable Fields - expanded and shifted east
      {
        key: 'field_1',
        fieldNo: 1,
        name: 'Field 1',
        acres: 8,
        kind: 'arable',
        rotationId: 'arable6',
        rotationIndex: 0,
        status: { cropNote: 'Fallow', stubble: false, tilth: 0.4 },
        x: 300,
        y: 90,
        w: 50,
        h: 120,
      },
      {
        key: 'field_2',
        fieldNo: 2,
        name: 'Field 2',
        acres: 8,
        kind: 'arable',
        rotationId: 'arable6',
        rotationIndex: 1,
        status: { cropNote: 'Fallow', stubble: true, tilth: 0.3 },
        x: 355,
        y: 90,
        w: 50,
        h: 120,
      },
      {
        key: 'field_3',
        fieldNo: 3,
        name: 'Field 3',
        acres: 8,
        kind: 'arable',
        rotationId: 'arable6',
        rotationIndex: 2,
        status: { cropNote: 'Fallow', stubble: false, tilth: 0.35 },
        x: 410,
        y: 90,
        w: 50,
        h: 120,
      },
      {
        key: 'field_4',
        fieldNo: 4,
        name: 'Field 4',
        acres: 8,
        kind: 'arable',
        rotationId: 'arable6',
        rotationIndex: 3,
        status: { cropNote: 'Fallow', stubble: false, tilth: 0.5 },
        x: 300,
        y: 220,
        w: 50,
        h: 120,
      },
      {
        key: 'field_5',
        fieldNo: 5,
        name: 'Field 5',
        acres: 8,
        kind: 'arable',
        rotationId: 'arable6',
        rotationIndex: 4,
        status: { cropNote: 'Fallow', stubble: false, tilth: 0.25 },
        x: 355,
        y: 220,
        w: 50,
        h: 120,
      },
      {
        key: 'field_6',
        fieldNo: 6,
        name: 'Field 6',
        acres: 8,
        kind: 'arable',
        rotationId: 'arable6',
        rotationIndex: 5,
        status: { cropNote: 'Fallow', stubble: true, tilth: 0.25 },
        x: 410,
        y: 220,
        w: 50,
        h: 120,
      },
    ],
    closes: [
      // Closes straddling the slope between the homestead and arable fields
      {
        key: 'close_1',
        closeNo: 1,
        name: 'Close 1',
        acres: 3,
        kind: 'close',
        rotationId: 'close3',
        rotationIndex: 0,
        status: { cropNote: 'Fallow', stubble: false, tilth: 0.25 },
        x: 150,
        y: 110,
        w: 45,
        h: 80,
      },
      {
        key: 'close_2',
        closeNo: 2,
        name: 'Close 2',
        acres: 3,
        kind: 'close',
        rotationId: 'close3',
        rotationIndex: 1,
        status: { cropNote: 'Fallow', stubble: false, tilth: 0.25 },
        x: 200,
        y: 110,
        w: 45,
        h: 80,
      },
      {
        key: 'close_3',
        closeNo: 3,
        name: 'Close 3',
        acres: 3,
        kind: 'close',
        rotationId: 'close3',
        rotationIndex: 2,
        status: { cropNote: 'Fallow', stubble: false, tilth: 0.25 },
        x: 250,
        y: 110,
        w: 45,
        h: 80,
      },
    ],
  },
});

export default CONFIG_PACK_V1;
