export const CONFIG_PACK_V1 = Object.freeze({
  version: 1,
  units: { grain: 'bu', hay: 't' },
  time: {
    simMinPerRealMin: 60,
    tickSimMin: 0.5,
    daySimMin: 24 * 60,
    realMsPerMinute: 60 * 1000,
    minutesPerHour: 60,
    workStartMin: 6 * 60,
    workEndMin: 18 * 60,
    daylightAnchors: [
      { monthIndex: 0, workStart: 6 * 60, workEnd: 18 * 60 },
      { monthIndex: 1, workStart: 5 * 60 + 30, workEnd: 19 * 60 + 30 },
      { monthIndex: 2, workStart: 5 * 60, workEnd: 20 * 60 + 30 },
      { monthIndex: 3, workStart: 4 * 60 + 45, workEnd: 21 * 60 },
      { monthIndex: 4, workStart: 5 * 60 + 15, workEnd: 20 * 60 + 30 },
      { monthIndex: 5, workStart: 5 * 60 + 45, workEnd: 19 * 60 + 30 },
      { monthIndex: 6, workStart: 6 * 60 + 30, workEnd: 18 * 60 },
      { monthIndex: 7, workStart: 7 * 60 + 15, workEnd: 17 * 60 },
    ],
    speedMultipliers: {
      PAUSE: 0,
      VERY_SLOW: 0.03,
      SLOW: 0.06,
      NORMAL: 0.12,
      FAST: 0.5,
      ULTRA: 2,
    },
  },
  calendar: {
    months: ['I', 'II', 'III', 'IV', 'V', 'VI', 'VII', 'VIII'],
    daysPerMonth: 20,
  },
  labour: {
    monthlyHours: 640,
    hoursPerDay: 8,
    crewSlots: 4,
    travelStepSimMin: 0.5,
  },
  rates: {
    ploughHarrow: 160,
    sow: 90,
    hoe: 60,
    harvest: 120,
    hayCut: 180,
    loadUnloadMarket: 30,
    gardenHours: 6,
  },
  rules: {
    minGrainReserve: 120,
    sellTurnipThreshold: 200,
    hayMin: 2,
    hayTarget: 6,
    grainKeep: 120,
    grainSurplus: 160,
    cashMin: 5,
    manifestValueMin: 20,
    labourValuePerMin: 0.1,
    marketCooldownSimMin: 24 * 60,
    cartCapacity: 60,
    closeFieldMaxSteps: 120,
    seedMinimums: { barley: 12, pulses: 10, oats: 12, wheat: 12 },
    oatsLowThreshold: 20,
    priceDrift: { months: [6, 7, 8], factor: 0.1 },
    marketHours: { open: 9 * 60, close: 17 * 60 },
    travelPenaltyCap: 5,
    debtHorizonHours: 48,
    manifestDiscounts: { essential: 0.7, seeds: 0.9, default: 1.2 },
    buyUtilityMultiplier: 1.2,
    seedKeys: ['barley', 'pulses', 'oats', 'wheat'],
  },
  estate: {
    farmhouse: { x: 23, y: 14 },
    market: { x: 8, y: 8 },
    byre: { x: 30, y: 14, w: 8, h: 5 },
    parcels: [
      {
        key: 'close_1',
        name: 'Close 1',
        acres: 3,
        kind: 'close',
        status: { cropNote: 'Fallow', stubble: false, tilth: 0.25 },
        x: 40,
        y: 10,
        w: 15,
        h: 10,
      },
      {
        key: 'close_2',
        name: 'Close 2',
        acres: 3,
        kind: 'close',
        status: { cropNote: 'Fallow', stubble: false, tilth: 0.25 },
        x: 40,
        y: 22,
        w: 15,
        h: 10,
      },
      {
        key: 'close_3',
        name: 'Close 3',
        acres: 3,
        kind: 'close',
        status: { cropNote: 'Fallow', stubble: false, tilth: 0.25 },
        x: 40,
        y: 34,
        w: 15,
        h: 10,
      },
      {
        key: 'field_1',
        name: 'Field 1',
        acres: 9,
        kind: 'arable',
        rotationIndex: 0,
        status: { cropNote: 'Fallow', stubble: false, tilth: 0.4 },
        x: 60,
        y: 10,
        w: 25,
        h: 15,
      },
      {
        key: 'field_2',
        name: 'Field 2',
        acres: 9,
        kind: 'arable',
        rotationIndex: 1,
        status: { cropNote: 'Fallow', stubble: true, tilth: 0.3 },
        x: 60,
        y: 27,
        w: 25,
        h: 15,
      },
      {
        key: 'field_3',
        name: 'Field 3',
        acres: 9,
        kind: 'arable',
        rotationIndex: 2,
        status: { cropNote: 'Fallow', stubble: false, tilth: 0.35 },
        x: 60,
        y: 44,
        w: 25,
        h: 15,
      },
      {
        key: 'field_4',
        name: 'Field 4',
        acres: 9,
        kind: 'arable',
        rotationIndex: 3,
        status: { cropNote: 'Fallow', stubble: false, tilth: 0.5 },
        x: 90,
        y: 10,
        w: 25,
        h: 15,
      },
      {
        key: 'field_5',
        name: 'Field 5',
        acres: 9,
        kind: 'arable',
        status: { cropNote: 'Fallow', stubble: false, tilth: 0.25 },
        x: 90,
        y: 27,
        w: 25,
        h: 15,
      },
      {
        key: 'field_6',
        name: 'Field 6',
        acres: 9,
        kind: 'arable',
        status: { cropNote: 'Fallow', stubble: true, tilth: 0.25 },
        x: 90,
        y: 44,
        w: 25,
        h: 15,
      },
      {
        key: 'orchard',
        name: 'Orchard',
        acres: 2,
        kind: 'orchard',
        status: { cropNote: 'Fruit trees', stubble: false, tilth: 0 },
        x: 10,
        y: 24,
        w: 12,
        h: 10,
        rows: 0,
        pasture: true,
      },
      {
        key: 'homestead',
        name: 'Homestead Garden',
        acres: 1,
        kind: 'garden',
        status: { cropNote: 'Kitchen beds', stubble: false, tilth: 0.4 },
        x: 10,
        y: 36,
        w: 12,
        h: 8,
        rows: 0,
      },
      {
        key: 'coppice',
        name: 'Coppice',
        acres: 2,
        kind: 'coppice',
        status: { cropNote: 'Woodland', stubble: false, tilth: 0 },
        x: 10,
        y: 10,
        w: 12,
        h: 12,
        rows: 0,
      },
    ],
  },
});

export default CONFIG_PACK_V1;
